--Roles
INSERT INTO ROLE(NAME,DESCRIPTION,CREATED_ON,UPDATED_ON) VALUES ('ROLE_ADMIN', 'Administration Role',now(),now());
INSERT INTO ROLE(NAME,DESCRIPTION,CREATED_ON,UPDATED_ON) VALUES ('ROLE_USER', 'User Role',now(),now());

--Users
INSERT INTO USERS(ID,USERNAME,SCREEN_NAME,PASSWORD,PASSWORD_HINT,FIRST_NAME,LAST_NAME,EMAIL,ACCOUNT_ACTIVE,CREATED_ON,UPDATED_ON) 
VALUES (1,'jwdani','Claytonian','Clayton','My town','James','Daniel','jwdani@yahoo.com',1,now(),now());

INSERT INTO USERS(ID,USERNAME,SCREEN_NAME,PASSWORD,PASSWORD_HINT,FIRST_NAME,LAST_NAME,EMAIL,ACCOUNT_ACTIVE,CREATED_ON,UPDATED_ON) 
VALUES (2,'dramayrat','Antiochist','Antioch','My town','Don','Ramayrat','dramayrat@gmail.com',1,now(),now());

--Users Roles
INSERT INTO USERS_ROLE VALUES(1,1);
INSERT INTO USERS_ROLE VALUES(1,2);
INSERT INTO USERS_ROLE VALUES(2,1);
INSERT INTO USERS_ROLE VALUES(2,2);